src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Driver\Mysqli\Initializer\Options;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Vich\UploaderBundle\Mapping\Annotation\Uploadable;

#[ORM\Entity(repositoryClass: PropertyRepository::class)]

/**
 *  @UniqueEntity("title")
 *  @Vich\Uploadable
 */
class Property
{
    
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;


    #[ORM\Column(type: 'string', length: 255)]
    /**
     * @Assert\Length(
     *      min = 5,
     *      max = 255)
     */
    private $title;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\Column(type: 'integer')]
    /**
     * @Assert\Range(min="10", max="400")
     */
    private $surface;

    #[ORM\Column(type: 'integer')]
    private $rooms;

    #[ORM\Column(type: 'integer')]
    private $bedrooms;

    #[ORM\Column(type: 'integer')]
    private $floor;

    #[ORM\Column(type: 'integer')]
    private $price;

    #[ORM\Column(type: 'string', length: 255)]
    private $city;

    #[ORM\Column(type: 'string', length: 255)]
    /**
     * @Assert\Regex("/^[0-9]{5}/")
     */
    private $postalcode;

    #[ORM\Column(type: 'boolean')]
    /**
     * @ options="default": false}
     */
    private $sold = false;

    #[ORM\Column(type: 'datetime')]

    private $ceatedAt;

    #[ORM\ManyToMany(targetEntity: Option::class, mappedBy: 'properties')]
    private $options;

    #[ORM\Column(type: 'string', length: 255)]
    /**
     * @ORM\Column(type="string")
     *
     * @var string|null
     */
    private $filename;

    
    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     * 
     * @var File|null
     * 
     */
    private $imageFile;

    #[ORM\Column(type: 'datetime')]
    private $updated_at;
    
   
    public function __construct()
    {
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice():string
    {
        return number_format($this->price,0,'',' ');
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalcode(): ?string
    {
        return $this->postalcode;
    }

    public function setPostalcode(string $postalcode): self
    {
        $this->postalcode = $postalcode;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCeatedAt(): ?\DateTimeInterface
    {
        return $this->ceatedAt;
    }

    public function setCeatedAt(\DateTimeInterface $ceatedAt): self
    {
        $this->ceatedAt = $ceatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Option>
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return null|string
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param null|string $filename
     * @return Property
     */
    public function setFilename(?string $filename): Property
    {
        $this->filename = $filename;

        return $this;
    }

    /**
     * @return null|File
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param null|File $imageFile
     * @return Property 
     */
    public function setImageFile(?File $imageFile): Property
    {
        $this->imageFile = $imageFile;

        if ($this->imageFile instanceof UploadedFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updated_at = new \DateTime('now');
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            
            ->add('options', EntityType::class, [
                'class'=> Option::class,
                'choice_label'=>'name',
                'multiple'=> true
            ])

            ->add('imageFile', FileType::class, [
                'required'=>false
            ])

            ->add('city')
            ->add('postalcode')
            ->add('sold')
            //->add('ceatedAt')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain'=>'form'
        ]);
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\ContactType;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;
use Doctrine\ORM\Mapping\Id;
use App\Repository\PropertyRepository;
use Doctrine\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use ContainerWKIk2Bf\PaginatorInterface_82dac15;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PropertyController extends AbstractController
{
    //dans index on recupere le repository(quand on a plusieur methode qui font appel au repository)
    public function __construct(PropertyRepository $repository)
    {
      $this->repository= $repository;  
      
    }
    
    #[Route('/biens', name: 'property.index')]
    public function index(PaginatorInterface  $paginator, Request $request): Response
    {
        
   
      $search=new PropertySearch();  

      $form = $this->createForm(PropertySearchType::class, $search);

      $form->handleRequest($request);
      
      
      $properties = $paginator->paginate($this->repository->findAllVisibleQuery($search),
        $request->query->getInt('page', 1),
        12/*la limite a mettre en place*/);
        /*$property[0]->setSold(true);
        $this->em->flush();*/
        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties',
            'properties'=>$properties,
            'form'=> $form->createView()
        ]);
    }

        
         /**
          * @Route("/biens-{id}", name= "property.show")
         * @param Property $property
         * @return response
         */

        public function show(Property $property, Request $request, ContactNotification $notification): Response
        {

          $contact= new Contact();

          $contact->setProperty($property);

          $form= $this->createForm(ContactType::class, $contact);

          $form->handleRequest($request);

          if ($form->isSubmitted() && $form->isValid()) {

            $notification->notify($contact);

            $this->addFlash('success', 'Votre email a bien ete envoye');

            /*$this->redirectToRoute('property.show', [
              'id'=> $property->getId()
            ]);*/
          } 

          // $property = $this->repository->find($id);
            return $this->render('property/show.html.twig', [
                'property'=> $property,
                'current_menu' => 'properties',
                'form'=> $form->createView()
            ]);
        }
    
}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tous nos biens!{% endblock %}

{% block body %}

<div class="jumbotron">
    <div class="container">
        {{ form_start(form) }}
        <div class="row">
            <div class="col">
                {{ form_row(form.maxPrice) }}
            </div>
            <div class="col">
                {{ form_row(form.minSurface) }}
            </div>
            <div class="col">
                <button class="btn btn-primary">Rechercher</button>
            </div>
        </div>
        {{ form_end(form) }}
    </div>
</div>

    <div class="container mt-4">
        <h1>Voir tout nos bien </h1>

        <div class="row">
        {% for properties in properties %}
            <div class="col-md-4">
                {% include "property/property.html.twig" %}
            </div>
        {% endfor %}
        </div>

        <div class="pagination">
            {{ knp_pagination_render(properties) }}
        </div>

    </div>

{% endblock %}

templates/property/property.html.twig
    <div class="card mb-4">
        {% if properties.filename %}
            <img src="{{ vich_uploader_asset(properties, 'imageFile') }}" alt="card-img-top" style="width: 100%; height:auto;">
        
        {% else %}
            <img src="{{ '/images/properties/Dessin1.png' }}" alt="card-img-top" style="width: 100%; height:auto;">
        {% endif %}
         
         <div class="card-body">
            <h5 class="card-title">
                <a href="{{ path ( 'property.show' , {id: properties.id}) }}" title="ciliquez poue en savoir plus sur le lien">{{ properties.title }}</a>
            </h5>
            <p class="card-text">{{ properties.surface }}m2 {{ properties.city }} ({{ properties.postalcode }}) </p>
            <div class="text-primary" style="font.size: 2rem; font-weight: bold;">{{ properties.formattedPrice }} £</div>
         </div>
        
    </div>

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title property.title %}



{% block body %}
    <div class"container mt-4">
        <div class="row">
            <div class="col-md-8">
                {% if property.filename %}
            <img src="{{ vich_uploader_asset(property, 'imageFile') }}" alt="card-img-top" style="width: 100%; height:auto;">
        
        {% else %}
            <img src="{{ '/images/properties/Dessin1.png' }}" alt="card-img-top" style="width: 100%; height:auto;">
        {% endif %}
            </div>
            <div class="col-md-4">
                <h1>{{ property.title }}</h1>
                <h2>{{ property.rooms }} pieces . {{ property.surface }} m2</h2>
                <div class="text-primary" style="font-size: 4rem; font-weight: bold;">{{ property.formattedPrice }} £</div>
                <a href="#" class="btn btn-primary"> Contactez l'agence</a>
                <div id="conctactForm" class="mt-4">
                    {{ form_start(form) }}
                    <div class="row">
                        <div class="col">{{ form_row(form.firstname) }}</div>
                        <div class="col">{{ form_row(form.lastname) }}</div>
                    </div>
                    <div class="row">
                        <div class="col">{{ form_row(form.phone) }}</div>
                        <div class="col">{{ form_row(form.message) }}</div>
                    </div>
                    {{ form_rest(form) }}
                    <div class="form-group">
                        <button class="btn btn-primary">Envoyer</button>
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>

        <p>
            {{ property.description | nl2br}}
        </p>

        <div class="row">
            <div class="cold-md-8">
                <h2>Caracteristique</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface Habitable</td>
                        <td>{{ property.surface }}</td>
                    </tr>
                     <tr>
                        <td>pieces</td>
                        <td>{{ property.rooms }}</td>
                    </tr>
                     <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                     <tr>
                        <td>Etape</td>
                        <td>{{ property.floor }}</td>
                    </tr>
                </table>

                </div>
                <div class="col-md-4">
                    <h2>Specificite</h2>
                       <ul class="list-group">
                        {% for option in property.options %}
                            <li class="list-group-item">{{ option.name }}<li>
                        {% endfor %}
                       </ul> 
                </div>

        </div>
    </div>
{% endblock %}